version: '3.8'
services:
  scrabble:
    build:
      context: .
    working_dir: /opt/workdir
    volumes:
      - type: bind
        source: .
        target: /opt/workdir
      - src_code:/opt/workdir/src
    # command: java -cp build/classes/java/main Game

  compiler-scrabble:
    build:
      context: .
    working_dir: /opt/workdir
    volumes:
      - type: bind
        source: .
        target: /opt/workdir
      - src_code:/opt/workdir/src
    command: find . -name "*.java" | entr -r javac $(fnd . -name "*.java")


volumes:
  src_code: